### ISSUE TITLE
Colors overlap in Bottom Navigation mode (Transition Glitch?)

### ISSUE THREAD

**Issue by ajitzero** [Eajy/MaterialDesignDemo#12]
In the "Bottom Navigation" section,

If I'm on the blue tab and I click on the red tab, then if I click on the yellow tab: there's a orange section on the first part, while the rest is yellow.

![Transition glitches?](https://i.imgur.com/bvyRCj0.jpg)

If I'm on the red tab and I click on the blue tab, then if I click on the green tab: there's a blue/green/teal section on the first part, while the rest is green.

![Not the same distribution everytime though](https://i.imgur.com/oVM0Smy.jpg)

It's **not** consistent but does happen with a mix of swiping & clicking on the tabs at either end quickly.

**Comment by Eajy** [comment]
Thanks. I have updated code to fix this problem.
