### ISSUE TITLE
androidx

### ISSUE THREAD

**Issue by zihan618** [Eajy/MaterialDesignDemo#18]
hello， why not try to migrate to androidx?
I tried to do that, but there seems to be something wrong in the migration process.
In the layout file, some attribute don't exist.

**Comment by Eajy** [comment]
Hi,
I think androidx and android support are two different types of developing
libs.
There are some differences in layout and many other things.
If you wanna using androidx I suggest you start with a new project.

**Comment by pvarry** [comment]
Hi, AndroidX and support are the same libraries, with AndroidX they repacked major Android and Google libraries like support, V4, design ... into new and more comprehensive names. They also added new content to Android Jetpack and new feature to "old" libraries using this new naming.

Side notes from Android doc: https://developer.android.com/topic/libraries/support-library 
With the release of Android 9.0 (API level 28) there is a new version of the support library called AndroidX which is part of Jetpack. The AndroidX library contains the existing support library and also includes the latest Jetpack components. 

You can continue to use the support library. Historical artifacts (those versioned 27 and earlier, and packaged as android.support.*) will remain available on Google Maven. However, all new library development will occur in the AndroidX library. 

We recommend using the AndroidX libraries in all new projects. You should also consider migrating existing projects to AndroidX as well.

**Comment by Eajy** [comment]
Well,
Ok. Google has made a guide of migrating to androidx:
https://developer.android.com/jetpack/androidx/migrate
But also if using androidx I wanna start with a new project.

- Eajy

**Comment by Gurupreet** [comment]
Yeh its easier to migrate from Android studio itself but many elements and there properties has to be refactored. May be not needed yet as many are still using Jetpack. Hopefully when most developers moved to AndroidX or Google only add all new widget in AndroidX only we can move but for now its fine not any big difference.

**Comment by Gurupreet** [comment]
Only new thing I really like that is in AndroidX but not in Jetpack is multiple select recyclerview. Lets see how many new things Google add in AndroidX along with launch of Android Q

**Comment by Eajy** [comment]
Yes, great idea!

- Eajy

**Comment by Eajy** [comment]
Already pushed a new project with MD2
