### ISSUE TITLE
DonateActivity

### ISSUE THREAD

**Issue by avipars** [Eajy/MaterialDesignDemo#5]
Your app looks really cool. And I appreciate how you uploaded your code to GitHub, Can you enlighten us with which IAB library you used and maybe post the donate activity?

**Comment by Eajy** [comment]
Hey, thank you for like this app.
The IAB I used that reference the Google's In-App-Purchase.
Here is the link:
https://developer.android.com/google/play/billing/index.html
And there is a demo in it. You can just copy that to use.

-- By Eajy

**Comment by avipars** [comment]
Thank you,most people use helper libraries, so I'm surprised you went with
their demo. I was looking in your code and was able to fix my app tab
layout by referencing your project. So thank you!
