### ISSUE TITLE
Failed to launch MainActivity

### ISSUE THREAD

**Issue by tabjy** [Eajy/MaterialDesignDemo#7]
Trying to compile and run on my phone, however failed to start. Here is what I did after clone this repo.

- adding `banner_ad_*` and `native_ad_*`  entries to `strings.xml`, just so I pass compiling
- commenting out _line 277_ and _278_ in `MainActivity.java`, as `DonateActivity` is not included in the source
- build and run

```
$ adb shell am start -n "com.eajy.materialdesigndemo/com.eajy.materialdesigndemo.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Error while executing: am start -n "com.eajy.materialdesigndemo/com.eajy.materialdesigndemo.activity.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=com.eajy.materialdesigndemo/.activity.MainActivity }
Error type 3
Error: Activity class {com.eajy.materialdesigndemo/com.eajy.materialdesigndemo.activity.MainActivity} does not exist.


Error while Launching activity
```

Android Studio version: 2.3.2
Android version: Android O Preview 1, API 26

It's most likely to be an error on my side, since the version I downloaded from Google Play works with no problem.

I'm sorry if the problem is obvious. I'm a beginner in Android developing. Thanks in advance.

**Comment by ghost** [comment]
Can you show me your debug log on the android side?

**Comment by Eajy** [comment]
Hey,
Hmm how about remove the showAd() method in Main1Fragment.


-- By Eajy

2017年6月8日 09:33，"Morgan Lee" <notifications@github.com>写道：

**Comment by tabjy** [comment]
Logcat was printed as below
```
06-07 23:17:40.017 5326-5326/? I/Finsky: [2] com.google.android.finsky.verifier.impl.br.c(103): Verification complete: id=5, package_name=com.eajy.materialdesigndemo
06-07 23:17:40.029 797-835/? I/PackageManager.DexOptimizer: Running dexopt (dexoptNeeded=1) on: /data/app/vmdl1329175940.tmp/base.apk pkg=com.eajy.materialdesigndemo isa=arm64 dexoptFlags=boot_complete,debuggable,public target-filter=interpret-only oatDir=/data/app/vmdl1329175940.tmp/oat sharedLibraries=null
06-07 23:17:41.443 797-814/? I/ActivityManager: Force stopping com.eajy.materialdesigndemo appid=10192 user=-1: installPackageLI
06-07 23:17:41.614 797-835/? I/PackageManager: Package com.eajy.materialdesigndemo codePath changed from /data/app/com.eajy.materialdesigndemo-7TrjlyHOcC7FNXUmMU_vug== to /data/app/com.eajy.materialdesigndemo-kK6FlaK8qQYjVf5LhUN4XQ==; Retaining data and using new
06-07 23:17:41.615 797-835/? W/PackageManager: Code path for com.eajy.materialdesigndemo changing from /data/app/com.eajy.materialdesigndemo-7TrjlyHOcC7FNXUmMU_vug== to /data/app/com.eajy.materialdesigndemo-kK6FlaK8qQYjVf5LhUN4XQ==
06-07 23:17:41.615 797-835/? W/PackageManager: Resource path for com.eajy.materialdesigndemo changing from /data/app/com.eajy.materialdesigndemo-7TrjlyHOcC7FNXUmMU_vug== to /data/app/com.eajy.materialdesigndemo-kK6FlaK8qQYjVf5LhUN4XQ==
06-07 23:17:42.223 512-855/? E/installd: Failed to unlink /data/dalvik-cache/arm64/data@app@com.eajy.materialdesigndemo-7TrjlyHOcC7FNXUmMU_vug==@base.apk@classes.dex: No such file or directory
                                         
                                         [ 06-07 23:17:42.224   512: 1057 E/         ]
                                         Couldn't opendir /data/app/vmdl1329175940.tmp: No such file or directory
06-07 23:17:42.224 797-835/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REMOVED dat=package:com.eajy.materialdesigndemo flg=0x4000010 (has extras) }: user 11 is stopped
06-07 23:17:42.225 797-835/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.eajy.materialdesigndemo flg=0x4000010 (has extras) }: user 11 is stopped
06-07 23:17:42.225 797-835/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.PACKAGE_REPLACED dat=package:com.eajy.materialdesigndemo flg=0x4000010 (has extras) }: user 11 is stopped
06-07 23:17:42.225 797-835/? W/ActivityManager: Skipping broadcast of Intent { act=android.intent.action.MY_PACKAGE_REPLACED flg=0x4000010 pkg=com.eajy.materialdesigndemo (has extras) }: user 11 is stopped
06-07 23:17:42.226 14125-14125/? I/Pm: Package com.eajy.materialdesigndemo installed in 2969 ms
06-07 23:17:42.490 797-4253/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 cmp=com.eajy.materialdesigndemo/.activity.MainActivity} from uid 2000
```

Well, things are getting a bit interesting now...

Rather than directly debugging on my physical device (a Nexus 6P), I created a AVD running API Level 25, and found out everything works perfectly.

So later on I discovered a pattern. if I manually build, or exporting from the AVD, a apk and install it **using GUI** (by clicking on the apk in file explorer), there is no problem. Otherwise, if the app is installed using adb, executing `adb install [-r] base.apk` or hitting `run` button in AS, the app cannot be found in my app drawer even though installation is said be to successful, and launching `MainActivity` using the adb command I previously mentioned would fail.

Furthermore, with manually installing the apk first, device no longer reports errors during deploying and running. So I gonna use this workaround.

Maybe this is a glitch with Android O itself. It looks be to out of the scope of this project. Anyway, your help is much more appreciated. This project has provided a professional example for beginners like me. Thank you very much!

**Comment by Eajy** [comment]
Hi,
Ok then. And I'm sorry that I don't know the reason of this situation.
However, hope this project is helpful to you. And hope you become a great
developer in the future.

-- By Eajy

2017年6月8日 14:24，"Tabjy" <notifications@github.com>写道：
